build:
    environment:
        node: '5.1.0'
    tests:
        before:
            - pip install pylint
        override: 
            -
              command: 'pylint  ./routersploit  --output-format=parseable  --reports=n --include-naming-hint=y | tee pylint-data'
              analysis:
                file: 'pylint-data'
                format: 'pylint-parseable'
